site_name: sorceress
site_url: https://github.com/altunenes/sorceress
nav:
  - Home: index.md
  - Contribution: contribution.md
  - API: api_reference.md
  - explanations: explanations of illusions.md
  - Javascripts:
    - about: jsanimations.md
    - footsteps: steps.html
    - eyes: eyes.html
    - lilac: lilac.html
    - motion: spatialmotion.html
    - blindness: blindness.html
    - blindness2: blindness2.html
    - Depth: depth.html
    - circles: circle.html
    - Length: length.html
    - Bright: bright.html
    - sine: crazysin.html
    - eeg: crazyeeg.html
    - phi: phi.html
    - coloradapt: cafter.html
theme:
  logo: assets/sitelogo.png
  name: material
  features:
    - search.suggests
    - content.tabs.link
    - navigation.tabs
    - navigation.tabs.sticky
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/altunenes
    - icon: fontawesome/brands/github
      link: https://github.com/altunenes